name: build

on:
  push: 
    branches: 
      - "main"
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v7

      - name: set up .net core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10'

      - name: list dotnet details
        run: dotnet --list-runtimes
          - dotnet --list-sdks

      - name: list files in root directory
        run: |
          Get-ChildItem -Path . | ForEach-Object { Write-Output $_.Name }
        shell: pwsh

      - name: build code
        run: dotnet build --configuration Release

      - name: publish code
        run: dotnet publish -c Release  --property:PublishDir="${{env.DOTNET_ROOT}}\myapp"

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
      
  
