name: log clean up workflow
description: This workflow calls log clean up share-workflow.

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow
permissions:
  actions: write
  artifact-metadata: write
  attestations: write
  checks: write
  code-quality: write
  contents: write
  deployments: write
  discussions: write
  drives: write
  issues: write
  models: read
  copilot-requests: write
  vulnerability-alerts: read

jobs:

  log_cleanup:

    uses:  yarynotsorg/shared-workflows/.github/workflows/reusable-workflow-log-cleanup.yml@main
    with:
      repo-name: ${{ github.repository }} 

    
