name: build solution
description: use reusable workflow to build solution

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  
  call-reusable-build-job:
    uses: YarynotsOrg/shared-workflows/.github/workflows/reusable-build.yml.yml@main
    with:
      the-solution: ReactApp1.slnx
    secrets:
      azure-profile: ${{ secrets.azure_profile }}
      
