name: Call Code Butler
description: call butler flow on issue comment

on:
  issue_comment:
    types: [created]

jobs:
  
  call-reusable-code-butler:
    uses: YarynotsOrg/shared-workflows/.github/workflows/reusable-code-butler.yml@main
    secrets:
      OPEN_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
