name: build solution
description: call butler flow on issue comment

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  
  call-reusable-code-butler:
    uses: YarynotsOrg/shared-workflows/.github/workflows/reusable-code-butler.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }} 
      
    
