name: clean up the logs
description: This workflow calls log clean up share-workflow.

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow
permissions:
  actions: write
  artifact-metadata: write
  attestations: write
  checks: write
  code-quality: write
  contents: write
  deployments: write
  discussions: write
  drives: write
  issues: write
  models: read
  copilot-requests: write
  vulnerability-alerts: read

jobs:

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
        
  log_cleanup:

    uses:  yarynotsorg/shared-workflows/.github/workflows/reusable-workflow-log-cleanup.yml@main
    with:
      repo-name: ${{ github.repository }} 

  message_team:

    uses: yarynotsorg/shared-workflows/.github/workflows/reusable-send-slack-msg.yml@main
    needs: log_cleanup
    with:
      message: "Log cleanup workflow has completed successfully."
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}



    
