name: test workflow
description: test workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:

  test_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Flow Triggered
        run: echo "flow triggered"
